"""update

Revision ID: 190bac9eaf80
Revises: 9ef3273b8aa2
Create Date: 2024-12-01 02:11:01.664222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '190bac9eaf80'
down_revision: Union[str, None] = '9ef3273b8aa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sources', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sources', type_='foreignkey')
    op.drop_column('sources', 'user_id')
    # ### end Alembic commands ###
