"""update

Revision ID: 43503347f89c
Revises: 359345ea13d6
Create Date: 2024-12-01 05:03:52.149003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43503347f89c'
down_revision: Union[str, None] = '359345ea13d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('last_connection', sa.Date(), nullable=True))
    op.add_column('connections', sa.Column('status', sa.String(), nullable=False))
    op.drop_column('connections', 'last_connections')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('last_connections', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('connections', 'status')
    op.drop_column('connections', 'last_connection')
    # ### end Alembic commands ###
