"""update

Revision ID: 359345ea13d6
Revises: db2e85915964
Create Date: 2024-12-01 04:43:42.216445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '359345ea13d6'
down_revision: Union[str, None] = 'db2e85915964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connections', 'last_connections',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connections', 'last_connections',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
