"""update

Revision ID: a6a6994c91b5
Revises: 4ec04dab121b
Create Date: 2024-11-30 14:17:45.362823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6a6994c91b5'
down_revision: Union[str, None] = '4ec04dab121b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('desciptions', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'desciptions')
    # ### end Alembic commands ###
