"""update

Revision ID: c0863c33a2b0
Revises: 13d479838490
Create Date: 2024-11-30 16:08:03.301366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0863c33a2b0'
down_revision: Union[str, None] = '13d479838490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('descriptions', sa.String(length=100), nullable=True))
    op.drop_column('models', 'desciptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('desciptions', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('models', 'descriptions')
    # ### end Alembic commands ###
